size = [1920, 1080]
reflective_boundary = false

shader = "shader.wgsl"

dx = 0.0810
dt = 0.0625

v = 340.29
amplitude = 1.0
frequency = 4.0 # in x100 Hz

[audio]
input = "../reverb/input.wav"
output = "output-left.wav"
pickup = [959, 540]           # left
# pickup = [961, 540] # right
