[package]
name = "wave_sim_gpu"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.83"
bytemuck = "1.15.0"
encase = "0.8.0"
nd_vec = "0.4.0"
pollster = "0.3.0"
soon = { git = "https://github.com/connorslade/misc" }
wgpu = "0.20.0"
winit = "0.30.0"
