# size = [1920, 1080]
size = [1440, 900]
reflective_boundary = false

map = "1440x900/map.png"
# map = "1440x900/axicon-map.png"
# map = "1440x900/fresnel-map.png"
# map = "1440x900/gradient-index-map.png"

dx = 5e-8
dt = 4e-10

v = 340_290_000
amplitude = 0.03
frequency = 4e14
