# size = [1920, 1080]
size = [1440, 900]
reflective_boundary = false

# map = "1440x900/axicon-map.png"
# map = "1440x900/fresnel-map.png"
# map = "1440x900/gradient-index-map.png"
map = "1440x900/map.png"

dx = 0.05
dt = 0.04

v = 340.29
amplitude = 0.03
frequency = 4.0
